GRANT ALL PRIVILEGES ON DATABASE wborderdb TO wbadmin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO wbadmin;

CREATE TABLE IF NOT EXISTS orders (
    order_uid TEXT PRIMARY KEY,
    date_created TIMESTAMP,
    data JSONB
);
